name: Security

on:
  push:
    branches: [main]
  pull_request:

permissions:
  security-events: write
  contents: read

jobs:
  weasel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: slvDev/weasel@main
        id: weasel
        with:
          version: nightly
          path: ./src
          min-severity: Low
          exclude: test,script
          sarif: true
          upload-sarif: true

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: weasel-report
          path: weasel-report.json
